---
title: "RSQLite"
output: html_document
date: "2024-04-05"
---

##**Databaseleri yükle **
```{r}
library(readxl)
Sales <- read_excel("Sales.xlsx")
Games<-read_excel("Games.xlsx")
```


##**Databaseleri birleştir**

```{r}
library(DBI)
library(RSQLite)
library(dplyr)
#con<-dbConnect(RSQLite::SQLite(), dbname = "veritabani.db")
#dbWriteTable(con, "Games", Games)
#dbWriteTable(con, "Sales", Sales)
# Inner join işlemini yapma
#dataJoined <- inner_join(Games, Sales, by = c("id","Name"))
#head(dataJoined)

#yeni üretilen tablo inidirildi
#library(openxlsx)
#write.xlsx(dataJoined, "dataJoined.xlsx")


```



##**Grafikleştir**

```{r}
library(ggplot2)
top_sales <- dataJoined %>%
  arrange(desc(Global_Sales)) %>%
  slice(1:10)

bar_plot <- ggplot(data = top_sales, aes(x = reorder(Name, Global_Sales), y = Global_Sales)) +
            geom_bar(stat = "identity", fill = "pink", color = "black") +
            labs(title = "En Yüksek Global Satışlar", x = "Oyun Adı", y = "Global Satışlar") +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            # Grafiğin boyutlarını artırın
            theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Grafiği görüntüleyelim
print(bar_plot)
```


